[book]
title = "LuminaTale"
authors = ["zzzzz167"]
language = "en"

[output.html]
additional-css = ["./theme/catppuccin.css"]
default-theme = "latte"
preferred-dark-theme = "mocha"
additional-js = ["./theme/mermaid.min.js", "./theme/mermaid-init.js"]

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
